from app_header import app
import app_header as site

core = site.core
application = app

# --- Exact-style compact BUZENT header logo ---
old_brand = '''<a class="buzent-brand" href="/" aria-label="BUZENT Home"><span class="brand-mark"><b>B</b><i></i><em>●</em><strong>●</strong></span><span class="brand-name">BU<span>Z</span>ENT</span></a>'''
new_brand = '''<a class="buzent-brand" href="/" aria-label="BUZENT Home">
<svg class="official-bz" viewBox="0 0 78 78" aria-hidden="true">
  <path d="M18 8h31c13 0 22 8 22 20 0 8-4 14-11 17 8 3 13 9 13 18 0 3-1 6-2 8H57c1-2 2-4 2-7 0-8-6-13-15-13H30V22h18c5 0 9 3 9 8s-4 8-9 8H31v31H18V8z" fill="#0A2A52"/>
  <path d="M11 61C18 42 29 25 48 15c-12 12-19 23-24 35-3 7-4 13-4 19-5-1-8-4-9-8z" fill="#D9A12E"/>
  <circle cx="34" cy="54" r="5" fill="#0A2A52"/>
  <circle cx="48" cy="54" r="5" fill="#D9A12E"/>
  <path d="M25 69c1-8 5-12 10-12 4 0 7 3 9 5 2-2 5-5 9-5 5 0 9 4 10 12H52c-1-4-2-5-4-5-1 0-2 1-3 2-1 1-2 1-3 0-1-1-2-2-4-2-2 0-3 1-4 5H25z" fill="#0A2A52"/>
  <path d="M43 65c2 0 3-1 4-2 1-1 2-1 3-1 3 0 5 2 6 7h7c-1-8-5-12-10-12-4 0-7 3-10 6z" fill="#D9A12E"/>
</svg>
<div class="brand-lockup"><span class="brand-name">BU<span>Z</span>ENT</span><small>BUSINESS × PROFESSIONAL TALENT</small></div></a>'''
core.BASE = core.BASE.replace(old_brand, new_brand)

# Header labels — only two public login choices.
core.BASE = core.BASE.replace('>Business Login<', '>Business Owner Login<')
core.BASE = core.BASE.replace('>Professional / Agency Login<', '>Professional / Agency Login<')

# Worldwide corporate network styling.
core.BASE = core.BASE.replace('</style></head>', '''<style>
nav{background:rgba(255,255,255,.97)!important;box-shadow:0 1px 0 rgba(7,26,52,.08)}
.nav{height:88px!important;gap:26px!important}.buzent-brand{display:flex!important;align-items:center!important;gap:12px!important;min-width:245px!important}.official-bz{width:48px;height:48px;display:block;flex:none}.brand-lockup{display:flex;flex-direction:column;gap:4px}.brand-name{font-family:'Manrope';font-weight:800!important;font-size:23px!important;line-height:1!important;letter-spacing:.18em!important;color:#08264B!important}.brand-name span{color:#D9A12E!important}.brand-lockup small{font-size:8px;letter-spacing:.14em;font-weight:700;color:#718096;white-space:nowrap}.links{gap:32px!important}.links a{font-weight:700;color:#475467}.actions .btn{border-radius:11px!important}.actions .ghost{background:#EEF5FF!important;color:#0C4A91!important}.actions .dark{background:linear-gradient(135deg,#071A34,#0B4B91)!important}
.world-hero{position:relative;overflow:hidden;border-radius:32px;padding:64px 56px;color:#fff;background:radial-gradient(circle at 78% 25%,rgba(30,136,229,.28),transparent 30%),radial-gradient(circle at 18% 75%,rgba(217,161,46,.16),transparent 28%),linear-gradient(135deg,#04152B 0%,#07356A 48%,#0A4E8E 100%);box-shadow:0 30px 90px rgba(5,36,76,.22)}.world-hero:before{content:'';position:absolute;inset:0;opacity:.33;background-image:radial-gradient(circle,#67B7FF 1.2px,transparent 1.3px);background-size:28px 28px;mask-image:linear-gradient(to right,rgba(0,0,0,.85),rgba(0,0,0,.3))}.world-hero>*{position:relative;z-index:2}.world-kicker{display:inline-flex;padding:8px 13px;border-radius:999px;border:1px solid rgba(255,255,255,.22);background:rgba(255,255,255,.08);font-weight:700;font-size:12px;letter-spacing:.08em}.world-hero h1{font-family:'Manrope';font-size:54px;line-height:1.06;max-width:900px;margin:18px 0 14px}.world-hero>p{max-width:860px;color:#DCEBFA;font-size:18px;line-height:1.7}.network-stage{display:grid;grid-template-columns:1fr 190px 1fr;gap:22px;align-items:center;margin-top:42px}.network-side{min-height:215px;padding:28px;border-radius:22px;background:linear-gradient(145deg,rgba(255,255,255,.13),rgba(255,255,255,.055));border:1px solid rgba(255,255,255,.18);backdrop-filter:blur(8px)}.network-side h3{font-size:22px;margin:0 0 10px}.network-side p{color:#DCE8F5;line-height:1.6}.network-hub{width:176px;height:176px;border-radius:50%;display:grid;place-items:center;text-align:center;margin:auto;background:radial-gradient(circle at 45% 35%,#1768B0,#061A35 72%);border:2px solid rgba(255,255,255,.78);box-shadow:0 0 0 9px rgba(255,255,255,.05),0 0 45px rgba(68,160,255,.45);position:relative}.network-hub:before{content:'';position:absolute;width:176px;height:176px;border-radius:50%;border:1px dashed rgba(217,161,46,.8);transform:scale(1.12)}.hub-logo{font:800 20px 'Manrope';letter-spacing:.19em}.hub-logo span{color:#E2AB3A}.hub-sub{display:block;margin-top:6px;font-size:10px;color:#BCD9F3;letter-spacing:.08em}.network-points{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:17px}.network-points div{background:#fff;border:1px solid #E6EAF0;border-radius:16px;padding:18px}.network-points b{display:block;color:#08264B;margin-bottom:5px}.account-shell{border-top:4px solid #0B4B91!important}.phone-block{display:grid;grid-template-columns:210px 1fr;gap:10px;align-items:end}.country-wrap{position:relative}.country-search{margin-bottom:7px!important;font-size:13px!important;padding:10px 11px!important}.country-select{font-size:14px}.login-type-label{font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#667085;margin-bottom:4px}
@media(max-width:1030px){.network-stage{grid-template-columns:1fr}.network-hub{order:2}.network-side{min-height:auto}.world-hero h1{font-size:44px}.buzent-brand{min-width:205px!important}.brand-lockup small{display:none}}
@media(max-width:760px){.world-hero{padding:36px 24px}.world-hero h1{font-size:36px}.network-points{grid-template-columns:1fr}.phone-block{grid-template-columns:1fr}.official-bz{width:42px;height:42px}.brand-name{font-size:19px!important}.buzent-brand{min-width:auto!important}.nav{height:auto!important}.links{display:none!important}}
</style></head>''')

# --- Corporate worldwide homepage ---
def polished_home():
    roles=''.join('<div class="card role"><h3>%s</h3><p class="muted">%s</p></div>'%(c,' • '.join(rs[:5])+(' • more' if len(rs)>5 else '')) for c,rs in core.ROLES.items())
    body='''<section class="world-hero"><span class="world-kicker">WORLDWIDE BUSINESS × PROFESSIONAL TALENT NETWORK</span><h1>The right business. The right expertise. Connected through BUZENT.</h1><p>BUZENT is a global professional platform where business owners find the people who can help them build, market, operate and grow — and where professionals, agencies and specialists find relevant business opportunities. One trusted network designed for stronger partnerships and mutual growth worldwide.</p><div class="network-stage"><div class="network-side"><h3>Business Owners</h3><p>Share what your business needs and discover relevant professionals, agencies and specialists based on role, capability and proof.</p><a class="btn light" href="/register/business">Join as a Business</a></div><div class="network-hub"><div><div class="hub-logo">BU<span>Z</span>ENT</div><small class="hub-sub">CONNECT • MATCH • GROW</small></div></div><div class="network-side"><h3>Professionals & Agencies</h3><p>Build credibility, showcase expertise and connect with businesses actively looking for the value you can provide.</p><a class="btn light" href="/register/pro">Join as Professional / Agency</a></div></div></section><section class="network-points" id="how"><div><b>01 — Define the Need</b><span class="muted">Businesses specify the expertise and outcome they are looking for.</span></div><div><b>02 — Build Trust</b><span class="muted">Professionals establish credibility through relevant profiles and evidence.</span></div><div><b>03 — Create the Right Connection</b><span class="muted">BUZENT brings both sides together around relevant opportunities.</span></div></section><section class="section" id="roles"><div class="head"><div><h2>The people behind every growing business</h2><p class="muted">Marketing, creative, technology, sales, finance, influence, consulting and agency expertise — available through one global professional network.</p></div></div><div class="grid">'''+roles+'''</div></section><section class="section" id="trust"><div class="card"><h2>Why BUZENT</h2><p class="muted">Business growth depends on the right people meeting at the right time. BUZENT is being built to make that discovery more credible, relevant and global — helping businesses find expertise and helping talent find genuine opportunities so both sides can grow together.</p></div></section>'''
    return core.page('Home',body)
core.app.view_functions['home']=polished_home

# --- Visible country code selectors with search ---
COUNTRIES = [
('India','+91'),('United States','+1'),('United Kingdom','+44'),('United Arab Emirates','+971'),('Saudi Arabia','+966'),('Singapore','+65'),('Australia','+61'),('Canada','+1'),('Germany','+49'),('France','+33'),('Netherlands','+31'),('Ireland','+353'),('New Zealand','+64'),('South Africa','+27'),('Malaysia','+60'),('Indonesia','+62'),('Philippines','+63'),('Japan','+81'),('South Korea','+82'),('Qatar','+974'),('Kuwait','+965'),('Oman','+968'),('Bahrain','+973'),('Sri Lanka','+94'),('Nepal','+977'),('Bangladesh','+880'),('Pakistan','+92'),('China','+86'),('Hong Kong','+852'),('Thailand','+66'),('Vietnam','+84'),('Brazil','+55'),('Mexico','+52'),('Spain','+34'),('Italy','+39'),('Switzerland','+41'),('Sweden','+46'),('Norway','+47'),('Denmark','+45'),('Belgium','+32'),('Austria','+43'),('Portugal','+351'),('Poland','+48'),('Turkey','+90'),('Israel','+972'),('Kenya','+254'),('Nigeria','+234')]

def _options(default='+91'):
    return ''.join(f'<option value="{code}" {"selected" if code==default else ""}>{name} ({code})</option>' for name,code in COUNTRIES)

def common_fields_polished():
    return f'''<div class="two"><div><label>Full Name</label><input name="name" required></div><div><label>Email Address</label><input type="email" name="email" required></div></div>
<label>Primary Mobile Number</label><div class="phone-block"><div class="country-wrap"><input class="country-search" type="text" placeholder="Search country or code" oninput="filterCountry(this,'primaryCode')"><select class="country-select" id="primaryCode" name="country_code" required>{_options()}</select></div><input name="phone" inputmode="numeric" placeholder="Mobile number" required></div>
<label>Alternate Mobile Number <span class="muted">(optional)</span></label><div class="phone-block"><div class="country-wrap"><input class="country-search" type="text" placeholder="Search country or code" oninput="filterCountry(this,'altCode')"><select class="country-select" id="altCode" name="alt_country_code">{_options()}</select></div><input name="alternate_phone" inputmode="numeric" placeholder="Alternate number"></div>
<div class="two"><div><label>Create Password</label><input type="password" name="password" minlength="8" required></div><div><label>Confirm Password</label><input type="password" name="confirm_password" minlength="8" required></div></div>
<p class="secure-note">Your email address must be verified by OTP before the account is activated.</p>
<script>function filterCountry(input,id){const q=input.value.toLowerCase();const s=document.getElementById(id);for(const o of s.options){const m=o.text.toLowerCase().includes(q)||o.value.toLowerCase().includes(q);o.hidden=!m;}if(q){for(const o of s.options){if(!o.hidden){s.value=o.value;break;}}}}</script>'''
site.common_fields = common_fields_polished
